### ISSUE TITLE
Foo 这个文件中只能导出一次，要把上面的export default 删除掉

### ISSUE THREAD

**Issue by huskylovegold** [luozhihao/redux-basic-example#5]
ERROR in ./src/containers/Foo.js
Module build failed: SyntaxError: D:/react-redux-demo/src/containers/Foo.js: Only one default export allowed per module. (39:0)

  37 |
  38 | // 利用connect将组件与Redux绑定起来
> 39 | export default connect(getList)(Foo)
     | ^

 @ ./src/containers/index.js 16:12-28

**Comment by luozhihao** [comment]
感谢指出，已修正
